### ISSUE TITLE
is it possible to have update feather in the menu

### ISSUE THREAD

**Issue by ageurtse** [Hieromon/AutoConnect#26] opened 2018-12-22 11:29 UTC
i would like to see a webupdate feather in the menu, now in the main file i add ArduinoOta.h and ESP8266HTTPUpdateServer.h.
But it would realy be nice that this is implemented within autoconnect.

**Comment by Hieromon** [comment] 2018-12-22 20:01
AutoConnectAux can separate some configuration screen into external files. You can define the following elements in its configuration.
- AutoConnectButton: Labeled button
- AutoConnectCheckbox: Labeled checkbox
- AutoConnectElement: General tag
- AutoConnectInput: Labeled text input box
- AutoConnectRadio: Labeled radio button
- AutoConnectSelect: Selection list
- AutoConnectSubmit: Submit button
- AutoConnectText: Style attributed text

You can load the external file described the above elements in JSON format from SPIFFS or SD and incorporate it into AutoConnectMenu. Each element can be accessed from the sketch. The values ​​of each element entered in the menu can be output to the stream, so you can save it to SPIFFS and reload it from SPIFFS.
Also, you can sketch the function that is called back when the AutoConnectAux page is requested from the menu. I added [an example](https://github.com/Hieromon/AutoConnect/tree/enhance/AutoConnectAux/examples/mqttRSSI_FS) using this feature, please experience it.
The [example](https://github.com/Hieromon/AutoConnect/tree/enhance/AutoConnectAux/examples/mqttRSSI_FS) publishes the RSSI of ESP8266 to the public cloud MQTT broker. I have released the Thingspeak channel for it. The access keys are as follows. Please enter from the AutoConnect menu.

- Server: mqtt.thingspeak.com
- Channel ID: 454951
- User Key: NRTFYGJ6TJFGX4RC
- API Key: HBVQ2XV6VYBI4582



It may be possible to isolate the OTA configuration screen and arbitrarily call it from the AutoConnectMenu to execute the OTA.

**Comment by ageurtse** [comment] 2018-12-23 13:03
Looking good, keep up the good working.
Know i'm trying to make my own project so i can go further with my wifi dimmer.

I am  not using the FS part, don't know how to upload the data folder using Sloeber.

**Comment by Hieromon** [comment] 2018-12-23 16:58
Yes, I also found it. Thank you feedback. I'm revising now.

**Comment by Hieromon** [comment] 2018-12-23 17:20
In about OTA and HTTP update, I examined the necessity and suitability of implementation.
I think the HTTPUpdater function can be implemented inside AutoConnect. It seems to have wide utility for users. Unless you know the internal structure of AutoConnect, it is difficult to use HTTPUpdater with the proper call sequence. If I have time to spare, I will implement it with v 0.97. But with an optimistic observation.
Is OTA necessary? It may be necessary for the ESP8266 module that does not have a serial interface.
I'm not sure.

**Comment by ageurtse** [comment] 2018-12-25 14:08
did you solve the problem with reading the settings ?

**Comment by Hieromon** [comment] 2018-12-26 13:53
Hello @ageurtse, Parameter values storing problem was solved, normal loading and saving of parameters will work. also it works fine with in SPIFFS.
But I have new difficult problems to solve. The problem is overwrite loading from Json.
For example, when placing radio buttons, write JSON as follows.
```json
{
  "name": "period",
  "type": "ACRadio",
  "label": "Update period",
  "value": [
    "30 sec.",
    "60 sec.",
    "180 sec."
  ],
  "arrange": "vertical",
  "checked": 1
}
```
The meanings of JSON object keys are as follows.
- name : Element name, you can handle it by "name" in sketches.
- type : Element type, ACRadio generates HTML tag as "<input type="radio" ...>".
- label: Label text for the Radio button.
- value: Radio button's label text. This is an array for putting radio buttons in the same group.
- arrange: An arrangement direction of buttons. (vertical or horizontal)
- checked: The number of the button checked in the array. (numerical)

And then, the Web page is generated as follows.

![img_0343](https://user-images.githubusercontent.com/12591771/50444645-01de7a00-094d-11e9-87a9-bac71b7cee59.JPG)

If you simply load it you will see that screen correctly. Input values ​​are also saved correctly, saving will work. But overwrite load does not work. There seems to be a problem with my implementation using std::vector<String> or std::vector<std::string>.
Overwrite loading is the ability to overwrite values ​​and attributes of previously loaded AutoConnectElemet. It is called as follows.
```c++
aux.loadElement(in, name);
```
It loads and overwrites elements specified by names from the stream or PROGMEM. 
The problem is when you increase array elements with overwriting loading. (the number of radio buttons above).
For example, suppose you load the following JSON additionally from another source.
```json
{
  "name": "period",
  "type": "ACRadio",
  "label": "Update period",
  "value": [
    "30 sec.",
    "60 sec.",
    "180 sec.",
    "240 sec."
  ],
  "arrange": "vertical",
  "checked": 1
}
```
It is necessary to add and display **&#x25CB;240 sec.**, but the screen will be blank. The generated whole HTML is lost. It seems that the generated HTML instance is destructed. Sometimes, reloading in the browser will display normally.
I found the source code location that is the direct trigger. The problem is in ```push_back``` of ```std::vector<String>``` or ```std::vector<std::string>```. Once releasing the allocated vectors once again and securing again, it seems that a memory leak occurs if it is larger than the previous number of elements. But I am not sure why the phenomenon happens.
Honest, is pretty tough...
I may need help from someone who is familiar with the combined implementation of ```std::vector``` and ```Arduino String```.
For now, I will update the development branch with a problematic version.

**Comment by ageurtse** [comment] 2018-12-26 14:03
Sorry to hear, this is way beyond my programming skills, so i can't help you. 

Why can't i use the loaded values in my sketch, it seems they aren't loaded. 

    AutoConnectInput&     hostnameElm = setting->getElement<AutoConnectInput>("hostname");
    AutoConnectInput&     mqttElm = setting->getElement<AutoConnectInput>("mqttserver");

    Serial.println("----------");
    Serial.println(hostnameElm.value);
    Serial.println(mqttElm.value);
    Serial.println("----------");

gives empty values.

**Comment by Hieromon** [comment] 2018-12-26 14:07
Problem diagnosis advanced a little. Maybe the cause is insufficient memory, but I'll manage.

**Comment by Hieromon** [comment] 2018-12-26 14:32
Sorry, my above comment is missing the point.

>Why can't i use the loaded values in my sketch, it seems they aren't loaded.

It's bug. I will do it by New Year's Eve...

**Comment by ageurtse** [comment] 2018-12-26 14:33
great, thanks a lot.
can't wait to see the next release, if i need to test something, let me know.

**Comment by Hieromon** [comment] 2018-12-28 22:17
@ageurtse, I updated develop branch. In my environment memory leaks seem to be fixed but I continue to test for a while.

**Comment by ageurtse** [comment] 2018-12-30 16:05
I will look into it, i'm trying to get my hardware for wifi dimmer to work.

**Comment by Hieromon** [comment] 2019-04-14 04:28
Incorporating the update function into the AutoConnect menu has been postponed in v 0.9.8. You can import WebUpdate in the way posted to Issue #50.
The ability to update the farm over the internet will be supported in v0.9.9 or later. Reopen this topic for reminding.

**Closed** 2019-09-07 15:25 UTC
Labels: enhancement
