### ISSUE TITLE
Autoconnectradio

### ISSUE THREAD

**Issue by smiley561** [Hieromon/AutoConnect#65] opened 2019-04-26 06:53 UTC
Hi,

on every reload of a page with an autoconnectradio, the "checked" attribute is 1 smaller than saved.

I would be glad about your help

**Comment by Hieromon** [comment] 2019-04-26 15:44
I confirmed the cause of the problem and made a simple mistake, sorry.
AutoConnectRadio indexer has incorrectly 0-based.  A patch was committed to master.

**Closed** 2019-04-27 06:46 UTC
Labels: bug
